import express from 'express';
import Reorder from '../models/Reorder.js';
import Medicine from '../models/Medicine.js';
import Order from '../models/Order.js';
import ActivityLog from '../models/ActivityLog.js';
import { authenticate, inventoryOrAdmin } from '../middleware/auth.js';
import { validateReorder, validateObjectId, validateQuery } from '../middleware/validation.js';
import { asyncHandler } from '../middleware/errorHandler.js';

const router = express.Router();

// @desc    Get all reorders
// @route   GET /api/reorders
// @access  Private (Inventory/Admin only)
const getReorders = asyncHandler(async (req, res) => {
  const { 
    page = 1, 
    limit = 10, 
    status, 
    reason, 
    priority,
    medicine,
    sort = 'createdAt',
    order = 'desc'
  } = req.query;
  
  // Build query
  const query = {};
  
  if (status) {
    query.status = status;
  }
  
  if (reason) {
    query.reason = reason;
  }
  
  if (priority) {
    query.priority = priority;
  }
  
  if (medicine) {
    query.medicine = medicine;
  }

  const sortOrder = order === 'desc' ? -1 : 1;
  const sortObj = { [sort]: sortOrder };

  const options = {
    page: parseInt(page),
    limit: parseInt(limit),
    sort: sortObj,
    populate: 'medicine triggeredBy approvedBy rejectedBy order'
  };

  const reorders = await Reorder.paginate(query, options);

  res.json({
    success: true,
    data: reorders
  });
});

// @desc    Get single reorder
// @route   GET /api/reorders/:id
// @access  Private (Inventory/Admin only)
const getReorder = asyncHandler(async (req, res) => {
  const reorder = await Reorder.findById(req.params.id)
    .populate('medicine triggeredBy approvedBy rejectedBy order');
  
  if (!reorder) {
    return res.status(404).json({
      success: false,
      message: 'Reorder not found'
    });
  }

  res.json({
    success: true,
    data: { reorder }
  });
});

// @desc    Create reorder
// @route   POST /api/reorders
// @access  Private (Inventory/Admin only)
const createReorder = asyncHandler(async (req, res) => {
  const { medicine, suggestedQuantity, reason, priority, notes } = req.body;

  // Get medicine details
  const medicineDoc = await Medicine.findById(medicine);
  if (!medicineDoc) {
    return res.status(404).json({
      success: false,
      message: 'Medicine not found'
    });
  }

  const reorder = await Reorder.create({
    medicine,
    suggestedQuantity,
    currentQuantity: medicineDoc.quantity,
    reorderLevel: medicineDoc.reorderLevel,
    reason,
    priority,
    notes,
    triggeredBy: req.user._id,
    status: 'pending',
    isAutoGenerated: false
  });

  // Log reorder creation
  await ActivityLog.createLog({
    action: 'reorder_suggested',
    entityType: 'reorder',
    entityId: reorder._id,
    userId: req.user._id,
    userRole: req.user.role,
    ipAddress: req.ip,
    userAgent: req.get('User-Agent'),
    severity: 'info',
    category: 'inventory',
    message: `Reorder suggested for ${medicineDoc.name} by ${req.user.name}`,
    details: { 
      medicine: medicineDoc.name,
      suggestedQuantity: reorder.suggestedQuantity,
      reason: reorder.reason,
      priority: reorder.priority
    }
  });

  res.status(201).json({
    success: true,
    message: 'Reorder created successfully',
    data: { reorder }
  });
});

// @desc    Update reorder
// @route   PUT /api/reorders/:id
// @access  Private (Inventory/Admin only)
const updateReorder = asyncHandler(async (req, res) => {
  const reorder = await Reorder.findById(req.params.id);
  
  if (!reorder) {
    return res.status(404).json({
      success: false,
      message: 'Reorder not found'
    });
  }

  // Only allow updates if reorder is pending
  if (reorder.status !== 'pending') {
    return res.status(400).json({
      success: false,
      message: 'Only pending reorders can be updated'
    });
  }

  const oldValues = {
    suggestedQuantity: reorder.suggestedQuantity,
    priority: reorder.priority,
    reason: reorder.reason,
    notes: reorder.notes
  };

  const updatedReorder = await Reorder.findByIdAndUpdate(
    req.params.id,
    req.body,
    { new: true, runValidators: true }
  ).populate('medicine triggeredBy approvedBy rejectedBy order');

  // Log reorder update
  await ActivityLog.createLog({
    action: 'reorder_updated',
    entityType: 'reorder',
    entityId: reorder._id,
    userId: req.user._id,
    userRole: req.user.role,
    ipAddress: req.ip,
    userAgent: req.get('User-Agent'),
    severity: 'info',
    category: 'inventory',
    message: `Reorder updated by ${req.user.name}`,
    details: { oldValues, newValues: req.body }
  });

  res.json({
    success: true,
    message: 'Reorder updated successfully',
    data: { reorder: updatedReorder }
  });
});

// @desc    Approve reorder
// @route   PUT /api/reorders/:id/approve
// @access  Private (Inventory/Admin only)
const approveReorder = asyncHandler(async (req, res) => {
  const { notes } = req.body;
  
  const reorder = await Reorder.findById(req.params.id);
  
  if (!reorder) {
    return res.status(404).json({
      success: false,
      message: 'Reorder not found'
    });
  }

  if (reorder.status !== 'pending') {
    return res.status(400).json({
      success: false,
      message: 'Only pending reorders can be approved'
    });
  }

  await reorder.approve(req.user._id, notes);

  // Create order from approved reorder
  const medicine = await Medicine.findById(reorder.medicine);
  const order = await Order.create({
    medicine: reorder.medicine,
    supplier: medicine.supplier || null,
    quantity: reorder.suggestedQuantity,
    unitPrice: medicine.cost || 0,
    totalPrice: (medicine.cost || 0) * reorder.suggestedQuantity,
    priority: reorder.priority,
    requestedBy: req.user._id,
    status: 'pending',
    notes: `Auto-generated from reorder ${reorder._id}`
  });

  // Mark reorder as ordered
  await reorder.markAsOrdered(order._id, req.user._id, 'Order created from approved reorder');

  // Log reorder approval
  await ActivityLog.createLog({
    action: 'reorder_approved',
    entityType: 'reorder',
    entityId: reorder._id,
    userId: req.user._id,
    userRole: req.user.role,
    ipAddress: req.ip,
    userAgent: req.get('User-Agent'),
    severity: 'info',
    category: 'inventory',
    message: `Reorder approved by ${req.user.name}`,
    details: { 
      orderId: order._id,
      orderNumber: order.orderNumber,
      notes
    }
  });

  res.json({
    success: true,
    message: 'Reorder approved successfully',
    data: { 
      reorder: await Reorder.findById(req.params.id).populate('medicine triggeredBy order'),
      order
    }
  });
});

// @desc    Reject reorder
// @route   PUT /api/reorders/:id/reject
// @access  Private (Inventory/Admin only)
const rejectReorder = asyncHandler(async (req, res) => {
  const { reason, notes } = req.body;
  
  const reorder = await Reorder.findById(req.params.id);
  
  if (!reorder) {
    return res.status(404).json({
      success: false,
      message: 'Reorder not found'
    });
  }

  if (reorder.status !== 'pending') {
    return res.status(400).json({
      success: false,
      message: 'Only pending reorders can be rejected'
    });
  }

  await reorder.reject(req.user._id, reason, notes);

  // Log reorder rejection
  await ActivityLog.createLog({
    action: 'reorder_rejected',
    entityType: 'reorder',
    entityId: reorder._id,
    userId: req.user._id,
    userRole: req.user.role,
    ipAddress: req.ip,
    userAgent: req.get('User-Agent'),
    severity: 'warning',
    category: 'inventory',
    message: `Reorder rejected by ${req.user.name}`,
    details: { reason, notes }
  });

  res.json({
    success: true,
    message: 'Reorder rejected successfully',
    data: { reorder: await Reorder.findById(req.params.id).populate('medicine triggeredBy') }
  });
});

// @desc    Get pending reorders
// @route   GET /api/reorders/pending
// @access  Private (Inventory/Admin only)
const getPendingReorders = asyncHandler(async (req, res) => {
  const reorders = await Reorder.findPending().populate('medicine triggeredBy');

  res.json({
    success: true,
    data: { reorders }
  });
});

// @desc    Get urgent reorders
// @route   GET /api/reorders/urgent
// @access  Private (Inventory/Admin only)
const getUrgentReorders = asyncHandler(async (req, res) => {
  const reorders = await Reorder.findUrgent().populate('medicine triggeredBy');

  res.json({
    success: true,
    data: { reorders }
  });
});

// @desc    Get auto-generated reorders
// @route   GET /api/reorders/auto
// @access  Private (Inventory/Admin only)
const getAutoReorders = asyncHandler(async (req, res) => {
  const reorders = await Reorder.findAutoGenerated().populate('medicine triggeredBy');

  res.json({
    success: true,
    data: { reorders }
  });
});

// @desc    Get overdue reorders
// @route   GET /api/reorders/overdue
// @access  Private (Inventory/Admin only)
const getOverdueReorders = asyncHandler(async (req, res) => {
  const { days = 7 } = req.query;
  const reorders = await Reorder.findOverdue(parseInt(days)).populate('medicine triggeredBy');

  res.json({
    success: true,
    data: { reorders }
  });
});

// @desc    Get reorders by reason
// @route   GET /api/reorders/reason/:reason
// @access  Private (Inventory/Admin only)
const getReordersByReason = asyncHandler(async (req, res) => {
  const { reason } = req.params;
  const reorders = await Reorder.findByReason(reason).populate('medicine triggeredBy');

  res.json({
    success: true,
    data: { reorders }
  });
});

// @desc    Update urgency score
// @route   PUT /api/reorders/:id/urgency
// @access  Private (Inventory/Admin only)
const updateUrgencyScore = asyncHandler(async (req, res) => {
  const reorder = await Reorder.findById(req.params.id);
  
  if (!reorder) {
    return res.status(404).json({
      success: false,
      message: 'Reorder not found'
    });
  }

  await reorder.updateUrgencyScore();

  res.json({
    success: true,
    message: 'Urgency score updated successfully',
    data: { 
      reorder: await Reorder.findById(req.params.id).populate('medicine triggeredBy'),
      urgencyScore: reorder.urgencyScore
    }
  });
});

// @desc    Get reorder statistics
// @route   GET /api/reorders/stats
// @access  Private (Inventory/Admin only)
const getReorderStats = asyncHandler(async (req, res) => {
  const totalReorders = await Reorder.countDocuments();
  const pendingReorders = await Reorder.countDocuments({ status: 'pending' });
  const approvedReorders = await Reorder.countDocuments({ status: 'approved' });
  const rejectedReorders = await Reorder.countDocuments({ status: 'rejected' });
  const orderedReorders = await Reorder.countDocuments({ status: 'ordered' });
  const autoGeneratedReorders = await Reorder.countDocuments({ isAutoGenerated: true });

  const statusStats = await Reorder.aggregate([
    { $group: { _id: '$status', count: { $sum: 1 } } }
  ]);

  const reasonStats = await Reorder.aggregate([
    { $group: { _id: '$reason', count: { $sum: 1 } } }
  ]);

  const priorityStats = await Reorder.aggregate([
    { $group: { _id: '$priority', count: { $sum: 1 } } }
  ]);

  const monthlyStats = await Reorder.aggregate([
    {
      $group: {
        _id: {
          year: { $year: '$createdAt' },
          month: { $month: '$createdAt' }
        },
        count: { $sum: 1 }
      }
    },
    { $sort: { '_id.year': -1, '_id.month': -1 } },
    { $limit: 12 }
  ]);

  res.json({
    success: true,
    data: {
      total: totalReorders,
      pending: pendingReorders,
      approved: approvedReorders,
      rejected: rejectedReorders,
      ordered: orderedReorders,
      autoGenerated: autoGeneratedReorders,
      byStatus: statusStats,
      byReason: reasonStats,
      byPriority: priorityStats,
      monthly: monthlyStats
    }
  });
});

// Routes
router.get('/', authenticate, inventoryOrAdmin, validateQuery, getReorders);
router.get('/stats', authenticate, inventoryOrAdmin, getReorderStats);
router.get('/pending', authenticate, inventoryOrAdmin, getPendingReorders);
router.get('/urgent', authenticate, inventoryOrAdmin, getUrgentReorders);
router.get('/auto', authenticate, inventoryOrAdmin, getAutoReorders);
router.get('/overdue', authenticate, inventoryOrAdmin, getOverdueReorders);
router.get('/reason/:reason', authenticate, inventoryOrAdmin, getReordersByReason);
router.get('/:id', authenticate, inventoryOrAdmin, validateObjectId, getReorder);
router.post('/', authenticate, inventoryOrAdmin, validateReorder, createReorder);
router.put('/:id', authenticate, inventoryOrAdmin, validateObjectId, updateReorder);
router.put('/:id/approve', authenticate, inventoryOrAdmin, validateObjectId, approveReorder);
router.put('/:id/reject', authenticate, inventoryOrAdmin, validateObjectId, rejectReorder);
router.put('/:id/urgency', authenticate, inventoryOrAdmin, validateObjectId, updateUrgencyScore);

export default router;

