import React, { useState, useEffect } from 'react';

const ReorderDemo = ({ medicines = [], onReorderUpdate }) => {
  const [reorders, setReorders] = useState([]);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [newReorder, setNewReorder] = useState({
    medicine: '',
    suggestedQuantity: 1,
    reason: 'manual',
    priority: 'normal',
    notes: ''
  });

  // Auto-generate reorder suggestions for low stock medicines
  useEffect(() => {
    const lowStockMedicines = medicines.filter(med => med.quantity <= med.reorderLevel);
    const autoSuggestions = lowStockMedicines.map(med => ({
      id: `auto-${med.id}-${Date.now()}`,
      medicineId: med.id,
      medicine: med.name,
      suggestedQuantity: Math.max(med.reorderLevel * 2, 50),
      currentQuantity: med.quantity,
      reorderLevel: med.reorderLevel,
      status: 'pending',
      reason: med.quantity === 0 ? 'out_of_stock' : 'low_stock',
      priority: med.quantity === 0 ? 'urgent' : 'high',
      createdAt: new Date().toLocaleString(),
      isAutoGenerated: true
    }));

    // Only add new suggestions if they don't already exist
    const existingIds = reorders.map(r => r.medicineId);
    const newSuggestions = autoSuggestions.filter(s => !existingIds.includes(s.medicineId));
    
    if (newSuggestions.length > 0) {
      setReorders(prev => [...newSuggestions, ...prev]);
    }
  }, [medicines]);

  const handleCreateReorder = () => {
    if (!newReorder.medicine || !newReorder.suggestedQuantity) {
      alert('Please fill in all required fields');
      return;
    }

    const selectedMedicine = medicines.find(m => m.id === parseInt(newReorder.medicine));
    if (!selectedMedicine) {
      alert('Medicine not found');
      return;
    }

    const reorder = {
      id: `manual-${Date.now()}`,
      medicineId: selectedMedicine.id,
      medicine: selectedMedicine.name,
      suggestedQuantity: parseInt(newReorder.suggestedQuantity),
      currentQuantity: selectedMedicine.quantity,
      reorderLevel: selectedMedicine.reorderLevel,
      status: 'pending',
      reason: newReorder.reason,
      priority: newReorder.priority,
      notes: newReorder.notes,
      createdAt: new Date().toLocaleString(),
      isAutoGenerated: false
    };

    setReorders(prev => [reorder, ...prev]);
    setNewReorder({
      medicine: '',
      suggestedQuantity: 1,
      reason: 'manual',
      priority: 'normal',
      notes: ''
    });
    setShowCreateForm(false);
  };

  const handleApprove = (reorderId) => {
    setReorders(prev => prev.map(r => 
      r.id === reorderId ? { ...r, status: 'approved' } : r
    ));
    onReorderUpdate && onReorderUpdate();
  };

  const handleReject = (reorderId) => {
    setReorders(prev => prev.map(r => 
      r.id === reorderId ? { ...r, status: 'rejected' } : r
    ));
  };

  const getStatusColor = (status) => {
    const colors = {
      pending: 'bg-yellow-100 text-yellow-800',
      approved: 'bg-green-100 text-green-800',
      rejected: 'bg-red-100 text-red-800',
      ordered: 'bg-blue-100 text-blue-800'
    };
    return colors[status] || 'bg-gray-100 text-gray-800';
  };

  const getPriorityColor = (priority) => {
    const colors = {
      low: 'bg-gray-100 text-gray-800',
      normal: 'bg-blue-100 text-blue-800',
      high: 'bg-orange-100 text-orange-800',
      urgent: 'bg-red-100 text-red-800'
    };
    return colors[priority] || 'bg-gray-100 text-gray-800';
  };

  const getReasonText = (reason) => {
    const reasons = {
      low_stock: 'Low Stock',
      out_of_stock: 'Out of Stock',
      expiring_soon: 'Expiring Soon',
      high_demand: 'High Demand',
      manual: 'Manual',
      auto: 'Auto'
    };
    return reasons[reason] || reason;
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-gray-900">Reorder Suggestions</h2>
        <div className="flex gap-2">
          <button
            onClick={() => setShowCreateForm(!showCreateForm)}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            {showCreateForm ? 'Cancel' : 'Create Manual Reorder'}
          </button>
        </div>
      </div>

      {/* Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white p-4 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Total Suggestions</h3>
          <p className="text-2xl font-bold text-gray-900">{reorders.length}</p>
        </div>
        <div className="bg-white p-4 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Pending</h3>
          <p className="text-2xl font-bold text-yellow-600">
            {reorders.filter(r => r.status === 'pending').length}
          </p>
        </div>
        <div className="bg-white p-4 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Approved</h3>
          <p className="text-2xl font-bold text-green-600">
            {reorders.filter(r => r.status === 'approved').length}
          </p>
        </div>
        <div className="bg-white p-4 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Rejected</h3>
          <p className="text-2xl font-bold text-red-600">
            {reorders.filter(r => r.status === 'rejected').length}
          </p>
        </div>
      </div>

      {/* Create Form */}
      {showCreateForm && (
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-lg font-semibold mb-4">Create Manual Reorder</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Medicine *
              </label>
              <select
                value={newReorder.medicine}
                onChange={(e) => setNewReorder({ ...newReorder, medicine: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                required
              >
                <option value="">Select Medicine</option>
                {medicines.map((med) => (
                  <option key={med.id} value={med.id}>
                    {med.name} (Current: {med.quantity}, Reorder Level: {med.reorderLevel})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Suggested Quantity *
              </label>
              <input
                type="number"
                min="1"
                value={newReorder.suggestedQuantity}
                onChange={(e) => setNewReorder({ ...newReorder, suggestedQuantity: parseInt(e.target.value) })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Reason
              </label>
              <select
                value={newReorder.reason}
                onChange={(e) => setNewReorder({ ...newReorder, reason: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="manual">Manual</option>
                <option value="low_stock">Low Stock</option>
                <option value="out_of_stock">Out of Stock</option>
                <option value="expiring_soon">Expiring Soon</option>
                <option value="high_demand">High Demand</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Priority
              </label>
              <select
                value={newReorder.priority}
                onChange={(e) => setNewReorder({ ...newReorder, priority: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="low">Low</option>
                <option value="normal">Normal</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Notes
              </label>
              <textarea
                value={newReorder.notes}
                onChange={(e) => setNewReorder({ ...newReorder, notes: e.target.value })}
                rows="3"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Additional notes for this reorder..."
              />
            </div>
          </div>

          <div className="flex gap-2 mt-4">
            <button
              onClick={handleCreateReorder}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              Create Reorder
            </button>
            <button
              onClick={() => setShowCreateForm(false)}
              className="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Reorders Table */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        {reorders.length === 0 ? (
          <div className="p-8 text-center text-gray-500">
            <p>No reorder suggestions found.</p>
            <p className="text-sm mt-2">Add medicines with low stock to see auto-generated suggestions.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Medicine
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Quantity
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Priority
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Reason
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Created
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {reorders.map((reorder) => (
                  <tr key={reorder.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">
                        {reorder.medicine}
                      </div>
                      <div className="text-sm text-gray-500">
                        Current: {reorder.currentQuantity} | Reorder Level: {reorder.reorderLevel}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {reorder.suggestedQuantity}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStatusColor(reorder.status)}`}>
                        {reorder.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getPriorityColor(reorder.priority)}`}>
                        {reorder.priority}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {getReasonText(reorder.reason)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {reorder.createdAt}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      {reorder.status === 'pending' && (
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleApprove(reorder.id)}
                            className="text-green-600 hover:text-green-900"
                          >
                            Approve
                          </button>
                          <button
                            onClick={() => handleReject(reorder.id)}
                            className="text-red-600 hover:text-red-900"
                          >
                            Reject
                          </button>
                        </div>
                      )}
                      {reorder.status === 'approved' && (
                        <span className="text-green-600">Approved</span>
                      )}
                      {reorder.status === 'rejected' && (
                        <span className="text-red-600">Rejected</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default ReorderDemo;

