import mongoose from 'mongoose';

const reorderSchema = new mongoose.Schema({
  medicine: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Medicine',
    required: [true, 'Medicine is required']
  },
  suggestedQuantity: {
    type: Number,
    required: [true, 'Suggested quantity is required'],
    min: [1, 'Suggested quantity must be at least 1']
  },
  currentQuantity: {
    type: Number,
    required: [true, 'Current quantity is required'],
    min: [0, 'Current quantity cannot be negative']
  },
  reorderLevel: {
    type: Number,
    required: [true, 'Reorder level is required'],
    min: [0, 'Reorder level cannot be negative']
  },
  status: {
    type: String,
    required: [true, 'Status is required'],
    enum: {
      values: ['pending', 'approved', 'rejected', 'ordered', 'cancelled'],
      message: 'Status must be one of: pending, approved, rejected, ordered, cancelled'
    },
    default: 'pending'
  },
  priority: {
    type: String,
    enum: ['low', 'normal', 'high', 'urgent'],
    default: 'normal'
  },
  reason: {
    type: String,
    required: [true, 'Reason is required'],
    enum: {
      values: ['low_stock', 'out_of_stock', 'expiring_soon', 'high_demand', 'manual', 'auto'],
      message: 'Reason must be one of: low_stock, out_of_stock, expiring_soon, high_demand, manual, auto'
    }
  },
  triggeredBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedAt: {
    type: Date
  },
  rejectedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  rejectedAt: {
    type: Date
  },
  rejectionReason: {
    type: String,
    trim: true,
    maxlength: [500, 'Rejection reason cannot exceed 500 characters']
  },
  order: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order'
  },
  openfdaData: {
    genericName: {
      type: String,
      trim: true
    },
    brandName: {
      type: String,
      trim: true
    },
    manufacturer: {
      type: String,
      trim: true
    },
    ndc: {
      type: String,
      trim: true
    },
    description: {
      type: String,
      trim: true
    },
    warnings: [{
      type: String,
      trim: true
    }],
    indications: [{
      type: String,
      trim: true
    }],
    dosageForm: {
      type: String,
      trim: true
    },
    route: {
      type: String,
      trim: true
    },
    strength: {
      type: String,
      trim: true
    }
  },
  estimatedCost: {
    type: Number,
    min: [0, 'Estimated cost cannot be negative']
  },
  currency: {
    type: String,
    default: 'USD',
    enum: ['USD', 'EUR', 'GBP', 'INR', 'CAD', 'AUD']
  },
  notes: {
    type: String,
    trim: true,
    maxlength: [1000, 'Notes cannot exceed 1000 characters']
  },
  history: [{
    status: {
      type: String,
      required: true
    },
    changedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    changedAt: {
      type: Date,
      default: Date.now
    },
    reason: {
      type: String,
      trim: true,
      maxlength: [500, 'Reason cannot exceed 500 characters']
    },
    notes: {
      type: String,
      trim: true,
      maxlength: [1000, 'Notes cannot exceed 1000 characters']
    }
  }],
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  urgencyScore: {
    type: Number,
    min: 0,
    max: 100,
    default: 0
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes for better performance
reorderSchema.index({ medicine: 1 });
reorderSchema.index({ status: 1 });
reorderSchema.index({ priority: 1 });
reorderSchema.index({ reason: 1 });
reorderSchema.index({ createdAt: -1 });
reorderSchema.index({ isAutoGenerated: 1 });
reorderSchema.index({ urgencyScore: -1 });

// Virtual for days since creation
reorderSchema.virtual('daysSinceCreation').get(function() {
  const now = new Date();
  const creationDate = new Date(this.createdAt);
  const diffTime = now - creationDate;
  return Math.floor(diffTime / (1000 * 60 * 60 * 24));
});

// Virtual for stock deficit
reorderSchema.virtual('stockDeficit').get(function() {
  return Math.max(0, this.reorderLevel - this.currentQuantity);
});

// Virtual for suggested vs current ratio
reorderSchema.virtual('suggestedRatio').get(function() {
  if (this.currentQuantity === 0) return Infinity;
  return this.suggestedQuantity / this.currentQuantity;
});

// Static method to find reorders by status
reorderSchema.statics.findByStatus = function(status) {
  return this.find({ status }).populate('medicine triggeredBy approvedBy rejectedBy order');
};

// Static method to find pending reorders
reorderSchema.statics.findPending = function() {
  return this.find({ status: 'pending' }).populate('medicine triggeredBy');
};

// Static method to find auto-generated reorders
reorderSchema.statics.findAutoGenerated = function() {
  return this.find({ isAutoGenerated: true }).populate('medicine triggeredBy');
};

// Static method to find urgent reorders
reorderSchema.statics.findUrgent = function() {
  return this.find({
    $or: [
      { priority: 'urgent' },
      { urgencyScore: { $gte: 80 } },
      { reason: 'out_of_stock' }
    ]
  }).populate('medicine triggeredBy');
};

// Static method to find reorders by reason
reorderSchema.statics.findByReason = function(reason) {
  return this.find({ reason }).populate('medicine triggeredBy');
};

// Static method to find overdue reorders
reorderSchema.statics.findOverdue = function(days = 7) {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - days);
  
  return this.find({
    status: 'pending',
    createdAt: { $lt: cutoffDate }
  }).populate('medicine triggeredBy');
};

// Instance method to approve reorder
reorderSchema.methods.approve = function(approvedBy, notes = '') {
  this.status = 'approved';
  this.approvedBy = approvedBy;
  this.approvedAt = new Date();
  
  this.history.push({
    status: 'approved',
    changedBy: approvedBy,
    reason: 'Reorder approved',
    notes,
    changedAt: new Date()
  });
  
  return this.save();
};

// Instance method to reject reorder
reorderSchema.methods.reject = function(rejectedBy, reason, notes = '') {
  this.status = 'rejected';
  this.rejectedBy = rejectedBy;
  this.rejectedAt = new Date();
  this.rejectionReason = reason;
  
  this.history.push({
    status: 'rejected',
    changedBy: rejectedBy,
    reason,
    notes,
    changedAt: new Date()
  });
  
  return this.save();
};

// Instance method to mark as ordered
reorderSchema.methods.markAsOrdered = function(orderId, changedBy, notes = '') {
  this.status = 'ordered';
  this.order = orderId;
  
  this.history.push({
    status: 'ordered',
    changedBy,
    reason: 'Order created',
    notes,
    changedAt: new Date()
  });
  
  return this.save();
};

// Instance method to update urgency score
reorderSchema.methods.updateUrgencyScore = function() {
  let score = 0;
  
  // Base score from reason
  const reasonScores = {
    'out_of_stock': 100,
    'low_stock': 60,
    'expiring_soon': 40,
    'high_demand': 30,
    'manual': 20,
    'auto': 10
  };
  
  score += reasonScores[this.reason] || 0;
  
  // Add score based on days since creation
  const daysSince = this.daysSinceCreation;
  if (daysSince > 7) score += 30;
  else if (daysSince > 3) score += 20;
  else if (daysSince > 1) score += 10;
  
  // Add score based on stock deficit
  const deficit = this.stockDeficit;
  if (deficit > 0) {
    score += Math.min(30, deficit * 2);
  }
  
  this.urgencyScore = Math.min(100, score);
  return this.save();
};

// Instance method to add OpenFDA data
reorderSchema.methods.addOpenFDAData = function(data) {
  this.openfdaData = {
    genericName: data.generic_name || data.openfda?.generic_name?.[0],
    brandName: data.brand_name || data.openfda?.brand_name?.[0],
    manufacturer: data.manufacturer_name || data.openfda?.manufacturer_name?.[0],
    ndc: data.product_ndc || data.openfda?.product_ndc?.[0],
    description: data.description || data.openfda?.description?.[0],
    warnings: data.warnings || data.openfda?.warnings || [],
    indications: data.indications_and_usage || data.openfda?.indications_and_usage || [],
    dosageForm: data.dosage_form || data.openfda?.dosage_form?.[0],
    route: data.route || data.openfda?.route?.[0],
    strength: data.strength || data.openfda?.strength?.[0]
  };
  
  return this.save();
};

const Reorder = mongoose.model('Reorder', reorderSchema);

export default Reorder;

